apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-jenkins
spec:
  selector:
    matchLabels:
      app: my-jenkins
  replicas: 2
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
        - name: ''
      containers:
        - name: my-app
          image: ini080/jekins_push:latest
          ports:
            - containerPort: 8080
