apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-jenkins
spec:
  selector:
    matchLabels:
      app: my-jenkins
  replicas: 2
  template:
    metadata:
      labels:
        app: my-jenkins
    spec:
      imagePullSecrets:
        - name: ''
      containers:
        - name: my-jenkins
          image: jenkins_push:${dockerBuildTag}
          ports:
            - containerPort: 8080
